spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:  # we are telling spring cloud gateway to use service discovery to make routing decisions
      server:
        webflux:
          discovery:
            locator:
              enabled: false # we are disabling the default routing behavior, those routes taken from service discovery. those routes are created manually in Getwayserverapplication.java
              lower-case-service-id: true
          httpclient:  # hhtp timeout configuration for micoservices loans and cards were we didn't set cercuit breaker. because cercuit breaker has its own timeout configuration
            connect-timeout: 1000
            response-timeout: 3s
  data:
    redis:  # redis configuration for rate limiting
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "myBank Gateway Server Application"
    version: "3.0.0"

logging:  # enable logs generated by logging framework with type(level) Debug
  level:
    com:
      mybank:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default: # this means that this conf will be applied to all circuit breakers, if we want to create a specific conf for a specific circuit breaker we can do that by creating a new conf with the name of the circuit breaker instead of "default"
      slidingWindowSize: 10 # number of calls to consider for the circuit breaker to calculate the failure rate
      permittedNumberOfCallsInHalfOpenState: 2 # number of calls to consider for the circuit breaker to transition from half-open to closed state or to open state
      failureRateThreshold: 50 # percentage of calls that must fail for the circuit breaker to transition from closed to open state
      waitDurationInOpenState: 10000  # time in milliseconds that the circuit breaker will stay in open state before transitioning to half-open state