
server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # permet de créer les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  config:
   import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: # enabling shutdown endpoint to gracefully shutdown the application using shutdown actuator path to test de-registering from eureka server
    shutdown:
      access: unrestricted
  info: # enabling info endpoint
   env:
    enabled: true


eureka:   # for connecting to eureka server
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:  # info endpoint data at /actuator/info (this path is unabled so that's why we will make some changes in the section management related to actuator), it will be visible in eureka server that's why we are using it
  app:
    name: "loans"
    description: "myBank Loans Application"
    version: "3.0.0"

springdoc:
  swagger-ui:
    path: /docs