
server:
    port: 9020

spring:
    application:
      name : eventsender
    cloud:
      function:
        definition: email|sms

      stream:
        bindings:
          emailsms-in-0:
            destination: queue-communication
            group: ${spring.application.name}
          emailsms-out-0: # here we define the output binding
            destination: communication-queue
        kafka:
          binder:
            brokers:
              - localhost:9092

        default-binder: kafka # to specify which binder to use by default, if we don't specify it then the default binder will be rabbitmq as it is the first one defined in the properties file

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      connection-timeout: 10s

